# Generated by Django 4.2.16 on 2024-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takpede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jenis_hewan',
            field=models.CharField(blank=True, choices=[('Anjing', 'Anjing'), ('Kucing', 'Kucing')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_deskripsi',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
