# Generated by Django 4.2.16 on 2024-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takpede', '0002_customuser_jenis_hewan_customuser_short_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
