# Generated by Django 4.2.16 on 2025-01-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
